config/routes.rb
PwnpetWeb::Application.routes.draw do
  resources :machine_activations

  resource :session, :controller => 'session'

  config_vars

  resources :users
  resources :machines
  resources :kernel_infos
  resources :command_results
  resources :shell_sessions

  root :to => "session#show"

end

app/models/kernel_info.rb
# Identifies the kernel running on a computer.
class KernelInfo < ActiveRecord::Base
  # The machine whose kernel is tracked.
  belongs_to :machine
  validates :machine, :presence => true
  validates :machine_id, :uniqueness => true
  
  # Kernel name, e.g. Linux
  validates :name, :length => 0..64, :presence => true
  
  # Version of kernel package, e.g. 2.6.35-28-generic
  validates :release, :length => 0..64, :presence => true
  
  # Kernel build number, e.g. #49-Ubuntu SMP Tue Mar 1 14:39:03 UTC 2011
  validates :version, :length => 0..128, :presence => true
  
  # Machine architecture, e.g. x86_64
  validates :architecture, :length => 0..64, :presence => true

  # Kernel OS string, e.g. GNU/Linux.
  validates :os, :length => 1..64, :presence => true
  
  # Updates the information to match the current machine state.
  #
  # The updated attributes are not automatically saved to the database.
  #
  # Args:
  #    shell_session:: ShellSession instance to use; if not given, a new shell
  #                    will be opened, used, and closed
  #
  # Returns self, for call chaining.
  def update_from_shell(shell_session = nil)
    shell = shell_session || machine.shell('Update cached kernel information.')
    [
      [:name, '-s'], [:release, '-r'], [:version, '-v'], [:architecture, '-m'],
      [:os, '-o']
    ].each do |property, cli_arg|
      send :"#{property}=", shell.exec!("uname #{cli_arg}").strip
    end
    shell.close unless shell == shell_session
    self
  end
end

app/controllers/kernel_infos_controller.rb
class KernelInfosController < ApplicationController
  # GET /kernel_infos
  # GET /kernel_infos.xml
  def index
    @kernel_infos = KernelInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kernel_infos }
    end
  end

  # GET /kernel_infos/1
  # GET /kernel_infos/1.xml
  def show
    @kernel_info = KernelInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @kernel_info }
    end
  end

  # GET /kernel_infos/new
  # GET /kernel_infos/new.xml
  def new
    @kernel_info = KernelInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @kernel_info }
    end
  end

  # GET /kernel_infos/1/edit
  def edit
    @kernel_info = KernelInfo.find(params[:id])
  end

  # POST /kernel_infos
  # POST /kernel_infos.xml
  def create
    @kernel_info = KernelInfo.new(params[:kernel_info])

    respond_to do |format|
      if @kernel_info.save
        format.html { redirect_to(@kernel_info, :notice => 'Kernel info was successfully created.') }
        format.xml  { render :xml => @kernel_info, :status => :created, :location => @kernel_info }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @kernel_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /kernel_infos/1
  # PUT /kernel_infos/1.xml
  def update
    @kernel_info = KernelInfo.find(params[:id])

    respond_to do |format|
      if @kernel_info.update_attributes(params[:kernel_info])
        format.html { redirect_to(@kernel_info, :notice => 'Kernel info was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @kernel_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kernel_infos/1
  # DELETE /kernel_infos/1.xml
  def destroy
    @kernel_info = KernelInfo.find(params[:id])
    @kernel_info.destroy

    respond_to do |format|
      format.html { redirect_to(kernel_infos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/kernel_infos_helper.rb
module KernelInfosHelper
end

app/views/kernel_infos/_form.html.erb
<%= form_for(@kernel_info) do |f| %>
  <% if @kernel_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kernel_info.errors.count, "error") %> prohibited this kernel_info from being saved:</h2>

      <ul>
      <% @kernel_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :architecture %><br />
    <%= f.text_field :architecture %>
  </div>
  <div class="field">
    <%= f.label :os %><br />
    <%= f.text_field :os %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kernel_infos/edit.html.erb
<h1>Editing kernel_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @kernel_info %> |
<%= link_to 'Back', kernel_infos_path %>

app/views/kernel_infos/index.html.erb
<h1>Listing kernel_infos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Release</th>
    <th>Version</th>
    <th>Architecture</th>
    <th>Os</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kernel_infos.each do |kernel_info| %>
  <tr>
    <td><%= kernel_info.name %></td>
    <td><%= kernel_info.release %></td>
    <td><%= kernel_info.version %></td>
    <td><%= kernel_info.architecture %></td>
    <td><%= kernel_info.os %></td>
    <td><%= link_to 'Show', kernel_info %></td>
    <td><%= link_to 'Edit', edit_kernel_info_path(kernel_info) %></td>
    <td><%= link_to 'Destroy', kernel_info, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kernel info', new_kernel_info_path %>

app/views/kernel_infos/new.html.erb
<h1>New kernel_info</h1>

<%= render 'form' %>

<%= link_to 'Back', kernel_infos_path %>

app/views/kernel_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @kernel_info.name %>
</p>

<p>
  <b>Release:</b>
  <%= @kernel_info.release %>
</p>

<p>
  <b>Version:</b>
  <%= @kernel_info.version %>
</p>

<p>
  <b>Architecture:</b>
  <%= @kernel_info.architecture %>
</p>

<p>
  <b>Os:</b>
  <%= @kernel_info.os %>
</p>


<%= link_to 'Edit', edit_kernel_info_path(@kernel_info) %> |
<%= link_to 'Back', kernel_infos_path %>