config/routes.rb
PwnpetWeb::Application.routes.draw do
  resources :machine_activations

  resource :session, :controller => 'session'

  config_vars

  resources :users
  resources :machines
  resources :kernel_infos
  resources :command_results
  resources :shell_sessions

  root :to => "session#show"

end

app/models/machine_activation.rb
# Tracks the process of placing a machine under PwnPet's control.
class MachineActivation < ActiveRecord::Base
  # The machine whose activation is tracked by this record.
  belongs_to :machine, :inverse_of => :activation
  validates :machine, :presence => true
  validates :machine_id, :uniqueness => true
  
  # Reset the password of the user account used to take control of the machine?
  validates :password_reset, :inclusion => [true, false]
  
  # If set, indicates when the machine got under PwnPet's control.
  validates :completed_at, :timeliness => { :type => :datetime,
                                            :allow_nil => true }

  # True if PwnPet gained control of this machine. 
  def completed?
    !!completed_at
  end
  
  # Makes a valiant attempt to take over the machine.
  #
  # This method resumes where it left off whenever possible.
  def attempt
    raise "Machine already activated" if completed?
    
    credentials = machine.ssh_credentials
    non_su_credential = credentials.select(&:needs_sudo).first
    su_credential = credentials.reject(&:needs_sudo).first
    non_su_credential ||= su_credential
    
    shell = nil
    
    begin
      # Learn about the machine's platform.
      unless machine.kernel_info
        return unless shell ||= machine.ssh(non_su_credential)
        kernel_info = machine.build_kernel_info
        kernel_info.update_from_shell shell
        return unless kernel_info.save
      end
      
      # Create and activate a superuser ssh credential.
      unless su_credential.healthy?
        return unless shell ||= machine.ssh(non_su_credential)
        su_credential ||= machine.ssh_credentials.build :username => 'root'
        su_credential.new_key!
        return unless su_credential.save
        su_credential.install shell
      end

      if password_reset && non_su_credential != su_credential
      end
      
      completed_at = Time.now
      save!
    ensure
      shell.close if shell
    end
    true
  end
end

app/controllers/machine_activations_controller.rb
class MachineActivationsController < ApplicationController
  # GET /machine_activations
  # GET /machine_activations.json
  def index
    @machine_activations = MachineActivation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @machine_activations }
    end
  end

  # GET /machine_activations/1
  # GET /machine_activations/1.json
  def show
    @machine_activation = MachineActivation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @machine_activation }
    end
  end

  # GET /machine_activations/new
  # GET /machine_activations/new.json
  def new
    @machine_activation = MachineActivation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @machine_activation }
    end
  end

  # GET /machine_activations/1/edit
  def edit
    @machine_activation = MachineActivation.find(params[:id])
  end

  # POST /machine_activations
  # POST /machine_activations.json
  def create
    @machine_activation = MachineActivation.new(params[:machine_activation])

    respond_to do |format|
      if @machine_activation.save
        format.html { redirect_to @machine_activation, :notice => 'Machine activation was successfully created.' }
        format.json { render :json => @machine_activation, :status => :created, :location => @machine_activation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @machine_activation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /machine_activations/1
  # PUT /machine_activations/1.json
  def update
    @machine_activation = MachineActivation.find(params[:id])

    respond_to do |format|
      if @machine_activation.update_attributes(params[:machine_activation])
        format.html { redirect_to @machine_activation, :notice => 'Machine activation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @machine_activation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_activations/1
  # DELETE /machine_activations/1.json
  def destroy
    @machine_activation = MachineActivation.find(params[:id])
    @machine_activation.destroy

    respond_to do |format|
      format.html { redirect_to machine_activations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/machine_activations_helper.rb
module MachineActivationsHelper
end

app/views/machine_activations/_form.html.erb
<%= form_for(@machine_activation) do |f| %>
  <% if @machine_activation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine_activation.errors.count, "error") %> prohibited this machine_activation from being saved:</h2>

      <ul>
      <% @machine_activation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :machine_id %><br />
    <%= f.number_field :machine_id %>
  </div>
  <div class="field">
    <%= f.label :password_reset %><br />
    <%= f.check_box :password_reset %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machine_activations/edit.html.erb
<h1>Editing machine_activation</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine_activation %> |
<%= link_to 'Back', machine_activations_path %>

app/views/machine_activations/index.html.erb
<h1>Listing machine_activations</h1>

<table>
  <tr>
    <th>Machine</th>
    <th>Password reset</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @machine_activations.each do |machine_activation| %>
  <tr>
    <td><%= machine_activation.machine_id %></td>
    <td><%= machine_activation.password_reset %></td>
    <td><%= link_to 'Show', machine_activation %></td>
    <td><%= link_to 'Edit', edit_machine_activation_path(machine_activation) %></td>
    <td><%= link_to 'Destroy', machine_activation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Machine activation', new_machine_activation_path %>

app/views/machine_activations/new.html.erb
<h1>New machine_activation</h1>

<%= render 'form' %>

<%= link_to 'Back', machine_activations_path %>

app/views/machine_activations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Machine:</b>
  <%= @machine_activation.machine_id %>
</p>

<p>
  <b>Password reset:</b>
  <%= @machine_activation.password_reset %>
</p>


<%= link_to 'Edit', edit_machine_activation_path(@machine_activation) %> |
<%= link_to 'Back', machine_activations_path %>