config/routes.rb
PwnpetWeb::Application.routes.draw do
  resources :machine_activations

  resource :session, :controller => 'session'

  config_vars

  resources :users
  resources :machines
  resources :kernel_infos
  resources :command_results
  resources :shell_sessions

  root :to => "session#show"

end

app/models/command_result.rb
# Records the result of a command issued in a shell session.
#
# CommandResults are created as soon as a command begins executing, and are
# modified throughout command execution.
class CommandResult < ActiveRecord::Base
  # The session during which the command was issued.
  belongs_to :shell_session, :inverse_of => :command_results
  validates :shell_session, :presence => true
  
  # The command line for the issued command.
  validates :command, :presence => true, :length => 1..1024
  
  # The exit code of the process that executed the command.
  validates :exit_code, :numericality => { :allow_nil => true,
      :integer_only => true, :greater_than_or_equal_to => 0 }
  # The data fed to the standard input of the process that executed the command.
  validates :stdin, :length => { :in => 0..64.kilobytes, :allow_nil => true }
  # The standard output of the process that executed the command.
  validates :stdout, :length => 0..64.kilobytes, :exclusion => [nil]
  # The standard error output of the process that executed the command.
  validates :stderr, :length => 0..64.kilobytes, :exclusion => [nil]
  
  # No attributes can be changed from a Web form.
  attr_accessible

  # True if the command's exit code indicates success.
  def succeeded?
    exit_code == 0
  end
  
  # True if the command finished executing.
  def completed?
    !exit_code.nil?
  end
  
  # Records the beginning of a command's execution.
  def start!(command, stdin = nil)
    raise "Command already finished executing" if completed?
    raise "Command already started executing" unless new_record?
    self.command = command
    self.stdin = stdin
    self.stdout = ''
    self.stderr = ''
    save!
    self
  end
  
  # Records new data coming from the standard output of the command's process.
  def append_to_stdout!(stdout_fragment)
    raise "Command already finished executing" if completed?
    self.stdout += stdout_fragment
    save!
    self
  end
  
  # Records new data coming from the standard error of the command's process.
  def append_to_stderr!(stderr_fragment)
    raise "Command already finished executing" if completed?
    self.stderr += stderr_fragment
    save!
    self
  end
  
  # Records the completion of the command's execution.
  def completed!(exit_code)
    raise "Command already finished executing" if completed?
    self.exit_code = exit_code
    save!
    self
  end
end

app/controllers/command_results_controller.rb
class CommandResultsController < ApplicationController
  # GET /command_results
  # GET /command_results.json
  def index
    @command_results = CommandResult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @command_results }
    end
  end

  # GET /command_results/1
  # GET /command_results/1.json
  def show
    @command_result = CommandResult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @command_result }
    end
  end

  # GET /command_results/new
  # GET /command_results/new.json
  def new
    @command_result = CommandResult.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @command_result }
    end
  end

  # GET /command_results/1/edit
  def edit
    @command_result = CommandResult.find(params[:id])
  end

  # POST /command_results
  # POST /command_results.json
  def create
    @command_result = CommandResult.new(params[:command_result])

    respond_to do |format|
      if @command_result.save
        format.html { redirect_to @command_result, :notice => 'Command result was successfully created.' }
        format.json { render :json => @command_result, :status => :created, :location => @command_result }
      else
        format.html { render :action => "new" }
        format.json { render :json => @command_result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /command_results/1
  # PUT /command_results/1.json
  def update
    @command_result = CommandResult.find(params[:id])

    respond_to do |format|
      if @command_result.update_attributes(params[:command_result])
        format.html { redirect_to @command_result, :notice => 'Command result was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @command_result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /command_results/1
  # DELETE /command_results/1.json
  def destroy
    @command_result = CommandResult.find(params[:id])
    @command_result.destroy

    respond_to do |format|
      format.html { redirect_to command_results_url }
      format.json { head :ok }
    end
  end
end

app/helpers/command_results_helper.rb
module CommandResultsHelper
end

app/views/command_results/_form.html.erb
<%= form_for(@command_result) do |f| %>
  <% if @command_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command_result.errors.count, "error") %> prohibited this command_result from being saved:</h2>

      <ul>
      <% @command_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shell_session_id %><br />
    <%= f.number_field :shell_session_id %>
  </div>
  <div class="field">
    <%= f.label :command %><br />
    <%= f.text_area :command %>
  </div>
  <div class="field">
    <%= f.label :stdin %><br />
    <%= f.text_area :stdin %>
  </div>
  <div class="field">
    <%= f.label :stdout %><br />
    <%= f.text_area :stdout %>
  </div>
  <div class="field">
    <%= f.label :stderr %><br />
    <%= f.text_area :stderr %>
  </div>
  <div class="field">
    <%= f.label :exit_code %><br />
    <%= f.number_field :exit_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/command_results/edit.html.erb
<h1>Editing command_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @command_result %> |
<%= link_to 'Back', command_results_path %>

app/views/command_results/index.html.erb
<h1>Listing command_results</h1>

<table>
  <tr>
    <th>Shell session</th>
    <th>Command</th>
    <th>Stdin</th>
    <th>Stdout</th>
    <th>Stderr</th>
    <th>Exit code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @command_results.each do |command_result| %>
  <tr>
    <td><%= command_result.shell_session_id %></td>
    <td><%= command_result.command %></td>
    <td><%= command_result.stdin %></td>
    <td><%= command_result.stdout %></td>
    <td><%= command_result.stderr %></td>
    <td><%= command_result.exit_code %></td>
    <td><%= link_to 'Show', command_result %></td>
    <td><%= link_to 'Edit', edit_command_result_path(command_result) %></td>
    <td><%= link_to 'Destroy', command_result, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command result', new_command_result_path %>

app/views/command_results/new.html.erb
<h1>New command_result</h1>

<%= render 'form' %>

<%= link_to 'Back', command_results_path %>

app/views/command_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Shell session:</b>
  <%= @command_result.shell_session_id %>
</p>

<p>
  <b>Command:</b>
  <%= @command_result.command %>
</p>

<p>
  <b>Stdin:</b>
  <%= @command_result.stdin %>
</p>

<p>
  <b>Stdout:</b>
  <%= @command_result.stdout %>
</p>

<p>
  <b>Stderr:</b>
  <%= @command_result.stderr %>
</p>

<p>
  <b>Exit code:</b>
  <%= @command_result.exit_code %>
</p>


<%= link_to 'Edit', edit_command_result_path(@command_result) %> |
<%= link_to 'Back', command_results_path %>