config/routes.rb
PwnpetWeb::Application.routes.draw do
  resources :machine_activations

  resource :session, :controller => 'session'

  config_vars

  resources :users
  resources :machines
  resources :kernel_infos
  resources :command_results
  resources :shell_sessions

  root :to => "session#show"

end

app/views/layouts/_footer.html.erb
<nav>
	<ul>
		<li>
      <a href="http://git.pwnb.us/pwnall/pwnpet_web">Source code</a>
		</li>
	</ul>
  <p class="design">
    Designed by <a href="http://www.costan.us">Victor Costan</a>
  </p>
</nav>

app/views/layouts/_header.html.erb
<hgroup>
  <h1>
    <span class="app-name">
      PwnPet
    </span>
  </h1>

  <%= render 'layouts/menu' %>
</hgroup>

app/views/layouts/_menu.html.erb
<nav>
  <ol>
    <li>
      <%= link_to 'Machines', machines_path %>
      <ol>
        <li><%= link_to 'All Machines', machines_path %></li>
        <li><%= link_to '+ Add Machine', new_machine_path %></li>
      </ol>
    </li>
    <li>
      <%= link_to 'Jobs', '#' %>
    </li>
    <li>
      <% if current_user %>
      <%= link_to current_user.email, '' %>
      <ol>
        <li><%= link_to 'Sign out', session_path, :method => :delete %></li>
        <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
      </ol>
      <% end %>
    </li>
  </ol>
</nav>

app/views/layouts/_status_bar.html.erb
<% if flash[:error] %>
<p class="status-bar error" data-pwnfx-reveal-target="status-bar">
  <%= flash[:error] %>

  <span class="actions">
  <%= link_to 'Hide', '#', 'data-pwnfx-reveal' => 'status-bar',
                           'data-pwnfx-reveal-trigger' => 'click-hide' %>
  </span>
</p>
<% elsif flash[:notice] %>
<p class="status-bar notice" data-pwnfx-reveal-target="status-bar">
  <%= flash[:notice] %>

  <span class="actions">
  <%= link_to 'Hide', '#', 'data-pwnfx-reveal' => 'status-bar',
                           'data-pwnfx-reveal-trigger' => 'click-hide' %>
  </span>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PwnPet</title>
<%= csrf_meta_tag %>
<%= favicon_link_tag %>
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'application' %>
</head>
<body>
<header>
<%= render 'layouts/header' %>
</header>

<div id="real-body">
<%= render 'layouts/status_bar' %>
<div id="content-wrapper">
<% unless @no_sidebar %>
<%= render 'session/sidebar' %>
<% end %>
<article id="main">
<%= yield %>
</article>
</div>
</div>

<footer>
<%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/layouts/config_vars.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= config_vars_app_name %> Vars</title>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <h1><%= config_vars_app_name %> Configuration Vars</h1>
<%= yield %>
  </body>
</html>